@startuml
title Get Restaurants (GET)

skinparam backgroundColor white
skinparam ParticipantBackgroundColor #E6E6E6
skinparam ParticipantBorderColor #666666
skinparam SequenceLifeLineBorderColor #999999
skinparam SequenceLifeLineBackgroundColor #FFFFFF
skinparam BoxBorderColor #666666
skinparam ArrowColor #333333
skinparam ActorBorderColor #666666
skinparam ActorBackgroundColor #E6E6E6

actor Client

participant "<<javaScript>>\n:server" as S
participant "<<router>>\n:restaurants" as R
participant "<<controllers>>\n:restaurants" as C
participant "<<model>>\n:Restaurant" as M
database "<<MongoDB>>\n:restaurants" as DB

Client -> S : req.get("/api/v1/restaurants")
activate S
S -> R : app.use("/api/v1/restaurants", restaurants)
activate R
R -> C : getRestaurants()
activate C
C -> M : find(query).populate("reservations")
activate M
M -> DB : RestaurantSchema\nfind(...)
activate DB
DB --> M : restaurants
deactivate DB
M --> C : restaurants
deactivate M
C --> Client : response (200)\n{success,count,data}
deactivate C
deactivate R
deactivate S
@enduml