@startuml
title Register User (POST)

skinparam backgroundColor white
skinparam ParticipantBackgroundColor #E6E6E6
skinparam ParticipantBorderColor #666666
skinparam SequenceLifeLineBorderColor #999999
skinparam ArrowColor #333333
skinparam ActorBorderColor #666666
skinparam ActorBackgroundColor #E6E6E6

actor Client

participant "<<javaScript>>\n:server" as S
participant "<<router>>\n:auth" as R
participant "<<controllers>>\n:auth" as C
participant "<<model>>\n:User" as M
database "<<MongoDB>>\n:users" as DB

Client -> S : req.post("/api/v1/auth/register")
activate S
S -> R : app.use("/api/v1/auth", auth)
activate R

R -> C : register()
activate C

C -> M : create(req.body)
activate M
M -> DB : UserSchema\ninsertOne(...)
activate DB
DB --> M : user
deactivate DB
M --> C : user
deactivate M

C -> M : getSignedJwtToken()
activate M
M --> C : token
deactivate M

C -> C : sendTokenResponse()

C --> Client : response (201)\n{success,token}\n+cookie(token)
deactivate C
deactivate R
deactivate S
@enduml
